version: '3.7'

services:
    mysql:
        # for mysql v8 we would want PR merged here for node https://github.com/mysqljs/mysql/pull/1962 + release
        image: mysql:5
        networks:
            - api
            - app

    api:
        build:
            context: ./api
            dockerfile: ./_docker/php/Dockerfile
        depends_on:
            - mysql
        environment:
            XDEBUG_HOST: ${XDEBUG_HOST}
        restart: on-failure
        networks:
            - api
            - blackfire
            - smtp

    nginx:
        build:
            context: ./api/_docker/nginx
        depends_on:
            - api
        networks:
            - api

    varnish:
        image: silverbackis/varnish:symfony4
        depends_on:
            - nginx
            - api
        networks:
            - api
            - app

    app:
        build:
            context: ./app
            dockerfile: _docker/Dockerfile
        depends_on:
            - mysql
        networks:
            - app

    blackfire:
        image: blackfire/blackfire
        env_file:
            - blackfire/.env.local
        networks:
            - blackfire

    smtp_relay:
        image: namshi/smtp
        restart: always
        networks:
            - smtp

volumes:
    db-mysql:

networks:
    app:
    api:
    blackfire:
    smtp:
