#!/usr/bin/env bash

RESET=$'\033[0m'
BOLD=$'\033[1m'
YELLOW=$'\033[32m'

function promptUser {
	local VAR
	read -p "$1 ${BOLD}${YELLOW}[$2]${RESET}: " VAR
  echo ${VAR:-$2}
}

if [ $# -eq 0 ]; then
  docker-compose ps
else
  if [[ "$@" == *"up"* ]]; then
    if [[ -z "${APP_ENV}" ]]; then
      PROD=$(promptUser "Are you running in production? ${BOLD}(y/n)${RESET}" "no")
      case ${PROD:0:1} in
          y|Y )
            APP_ENV="prod"
          ;;
          * )
            APP_ENV="dev"
          ;;
      esac
    fi
    OPS="-f docker-compose.yaml -f docker-compose-${APP_ENV}.yaml"
  else
    OPS=""
  fi
  CMD="docker-compose $OPS $@"
  echo ${CMD}
  eval ${CMD}
fi
