lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%kernel.project_dir%/%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 86400
